added one_liner test
DARTSG/shlomobot_pytest pull request #15
Opened 2022-11-16 03:45 UTC by ronpeer

2022-11-16 08:46 UTC, maxandron commented on shlomobot_pytest/utils.py
> +def get_functions_from_files(file_list: list[str]) -> Generator:
You can be specific in what the generator generates

```suggestion
def get_functions_from_files(file_list: list[str]) -> Generator[tuple[str, list[FunctionType]]]:
```

2022-11-16 08:50 UTC, maxandron commented on shlomobot_pytest/utils.py
> +def function_contains_regex(regex: str, function: FunctionType) -> bool:
regex might also be a compiled regex

```suggestion
def function_contains_regex(regex: str | re.Pattern, function: FunctionType) -> bool:
```

2022-11-16 08:51 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    )
A regular for loop will be better here for two reasons:
a. it will be more efficient since you can return True as soon as the regex is found
b. it's easier to read than a one liner

2022-11-16 08:53 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    for line in function_code.splitlines():
A comments to this block of code to make it easier to read

2022-11-16 08:53 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    return clean_lines
Add comments to this block of code to make it easier to read

2022-11-16 08:54 UTC, maxandron commented on shlomobot_pytest/utils.py
> +DEFINE_REGEX = r"^\s*def "
Since you define these outside, might as well compile them

2022-11-16 08:57 UTC, maxandron commented on shlomobot_pytest/utils.py
> +CLOSE_DOCSTRING_REGEX = r'.*?([\'"]+)$'
you can use `{3}` in regex to indicate you expect something to appear exactly 3 times

2022-11-16 09:00 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    docstring_state = {"is_active": False, "value": ""}
value -> docstring_type

You can actually keep the state in only one `docstring_type` variable

```python
docstring_type == "" # Not in docstring
docstring_type = '"""' # in """ type
docstring_type = "'''" # in ''' type
```

2022-11-17 01:31 UTC, KeshetS requested changes

2022-11-17 02:25 UTC, ronpeer commented on shlomobot_pytest/common_tests.py
> +    module = import_pyfile(py_filename)
to what?

2022-11-17 02:26 UTC, ronpeer commented on shlomobot_pytest/common_tests.py
>      module_code = inspect.getsource(module)
no it can not, because get_clean_function_lines is for a singular function, this is the entire file code

2022-11-17 03:02 UTC, maxandron commented on shlomobot_pytest/utils.py
> +            yield function.__name__, function
since the function contains the function name, yield that instead of a tuple (since you can get the name from the function)
Also, fix in other places that use `get_functions_from_files`

2022-11-17 03:04 UTC, maxandron commented on shlomobot_pytest/common_tests.py
> +    function_name = function.__name__
Since it's used only once, It doesn't provide any more value than calling `function.__name__` directly

2022-11-17 03:05 UTC, maxandron commented on shlomobot_pytest/common_tests.py
> +    builtins_list = [word for word in dir(builtins) if not re.match("[A-Z|_]", word[0])]
you don't need re.match since you are only checking on letter

```suggestion
    builtins_list = [word for word in dir(builtins) if word[0] not in "[A-Z|_]"]
```

2022-11-17 03:07 UTC, maxandron commented on shlomobot_pytest/common_tests.py
> +    builtins_list = [word for word in dir(builtins) if not re.match("[A-Z|_]", word[0])]
(`import string` for my suggestion)

2022-11-17 03:09 UTC, maxandron commented on shlomobot_pytest/common_tests.py
> +        ) or function_contains_regex(builtin_paramater_regex, function):
How about we just combine the two regexes?

Perhaps something like this can work?
```suggestion
        builtin_parameter_or_variable_pattern = f"({builtin_variable_regex})|({builtin_variable_regex})"
        if function_contains_regex(builtin_parameter_or_variable_pattern, function):
```

2022-11-17 03:13 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    split_code = list(filter(None, function_code.splitlines()))
Cool :D Add a comment above this line explaining that it removes empty lines (right?)
since its not obvious (I had to open the help for filter)

2022-11-17 03:14 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    split_code = list(filter(None, function_code.splitlines()))
it will miss any indented empty lines, no?
better would be to trim it first

```suggestion
    split_code = list(filter(lambda line: line.strip(), function_code.splitlines()))
```

2022-11-17 03:16 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    clean_lines = [split_code[0]]
```suggestion
    # The first line will be the definition of the function
    clean_lines = [split_code[0]]
```

2022-11-17 03:22 UTC, maxandron commented on shlomobot_pytest/utils.py
> +                clean_lines.append(line)
Minor change just to make it more efficient and avoid running the regex on every line

```suggestion
            # check if a multi-line docstring has started
            # since there is only one line of code before a docstring (the def line)
            # then when the docstring starts the length of the line list has to be 1
            if  len(clean_lines) == 1 and docstring_type == "" and and re.match(OPEN_DOCSTRING_REGEX, line):
                docstring_type = open_match.group()

            # Check if the previous multi-line docstring has closed
            elif docstring_type:
                close_match = re.match(CLOSE_DOCSTRING_REGEX, line)
                if close_match and close_match.group() == docstring_type:
                    docstring_type = ""

            else:
                clean_lines.append(line)
```

2022-11-17 03:25 UTC, maxandron commented on shlomobot_pytest/utils.py
> +
let's compile the regex here at the start if it's not a pattern yet

2022-11-17 04:58 UTC, maxandron commented
Reminder: add black to requirements.txt

2022-11-17 05:45 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    if type(regex) != re.Pattern:
use `instanceof` instead

2022-11-17 09:30 UTC, maxandron commented on shlomobot_pytest/utils.py
> +    ]
```suggestion
    split_code = list(filter(lambda line: line.strip(), function_code.splitlines()))
```

2022-11-17 09:39 UTC, merged