Refactor import checking to read from bytecode
DARTSG/shlomobot_pytest pull request #21
Opened 2022-11-30 03:37 UTC by kjdart

2022-11-30 06:24 UTC, KeshetS requested changes
Good job!

2022-11-30 06:24 UTC, KeshetS commented on shlomobot_pytest/common_tests.py
> +GLOBAL_DECLERATION_REGEX = re.compile(r"\n\s*global\s+[^\W]+(?:\s*,\s*[^\W]+\s*)*\n")
Why this was changed?

2022-11-30 06:24 UTC, KeshetS commented on shlomobot_pytest/common_tests.py
> +    """Checks if the all the required modules from import_list have been imported"""
Well done. Just add a comment that it doesn't check if unnecessary imports were made.

2022-11-30 07:50 UTC, kjdart commented on shlomobot_pytest/common_tests.py
> +GLOBAL_DECLERATION_REGEX = re.compile(r"\n\s*global\s+[^\W]+(?:\s*,\s*[^\W]+\s*)*\n")
I think I made an error when merging in the main branch. I've removed it in the latest commit

2022-11-30 07:53 UTC, kjdart commented on shlomobot_pytest/common_tests.py
> +    """Checks if the all the required modules from import_list have been imported"""
I've added the comment in the latest commit

2022-12-01 09:11 UTC, PHAng-DART reviewed
I am unsure if the correct_imports_are_made function will have the same problem as the function_contains_inputs function whereby the different python versions will generate different opcodes.

2022-12-07 05:47 UTC, KeshetS approved these changes

2022-12-07 05:47 UTC, merged