Refactor function_contains_input to use regex
DARTSG/shlomobot_pytest pull request #24
Opened 2022-12-01 08:49 UTC by kjdart

Refactors the implementation of `function_contains_input` to use regular expressions instead of reading function calls from bytecode.

This change is due to a [change in opcodes from Python 3.10 to 3.11](https://docs.python.org/3/whatsnew/3.11.html#cpython-bytecode-changes), making it easier for a regex implementation instead of rewriting the function for 3.11. However, this solution is less accurate. For example, it incorrectly returns True for `"input()"`.

An more accurate method would be to use `pytest-mock` to mock the builtin `input` function in the scope of the test function, then pass in a lambda to toggle a flag when called.

2022-12-01 09:23 UTC, PHAng-DART reviewed
I think the return for `input()` is alright because the student still used the input function to request for input. 

To ensure that the student includes a print statement in the input function, maybe changing the regex to `[^\w]input\(\"(.*)\"\)\\n` would help as it ensures that the student put a string inside the parameters for the input function.

2022-12-05 06:21 UTC, ronpeer requested changes

2022-12-05 06:21 UTC, ronpeer commented on shlomobot_pytest/common_tests.py
> +INPUT_REGEX = re.compile(r"[^\w]input\(")
regex will fail if any other class has an input method
for instance, if i use something like x.input() it will still work even though it is unintended
a fix would be a new regex INPUT_REGEX = re.compile(r"[^\w\.]input\(")

2022-12-05 06:34 UTC, kjdart commented on shlomobot_pytest/common_tests.py
> +INPUT_REGEX = re.compile(r"[^\w]input\(")
Fixed both suggestions in the latest commit

2022-12-05 07:05 UTC, ronpeer approved these changes

2022-12-06 03:17 UTC, merged