Completed the register_tests function to simplify the process of the pretest functions.
DARTSG/shlomobot_pytest pull request #30
Opened 2022-12-13 06:30 UTC by PHAng-DART

To use the function properly, need to import the register_tests function first, assign the file_function_map value, run the register_tests function with the required tests and then import the entire pretest.

Example:
`from shlomobot_pytest.pretest import register_tests

FILE_FUNCTION_MAP = {"phcode.py": []}

register_tests(
    FILE_FUNCTION_MAP,
    test_expected_files_exist={},
    test_expected_functions_exist={},
    test_pep8_compliant={},
    test_contains_main_function={
        "feedback":"Main function where?",
        "points_per_error":11,
        "max_points_deducted":11,
        "number_of_errors":2,
    },
    test_name_eq_main_statement_exist={
        "feedback":"Name = Main where?",
        "points_per_error":12,
        "max_points_deducted":12,
    },
    test_main_function_is_last_function={
        "feedback":"Why your main not last?",
    },
    test_docstring_exists={
        "feedback":"Docstring Where??",
    },
)

from shlomobot_pytest.pretest import *`

2022-12-14 07:53 UTC, maxandron requested changes

2022-12-14 07:53 UTC, maxandron commented on shlomobot_pytest/pretest.py
> +@pytest.mark.skip("Not Required")
What is all of that?

Instead of creating this function just add the functionality to globals() passed to register_functions

2022-12-14 07:53 UTC, maxandron commented on shlomobot_pytest/pretest.py
> +    file_function_map,
I don't think file_function_map should be part of this - instead, pass it as a parameter to the functions just like you do with other parameters

instead of this parameter, pass the globals as I mentioned in the comment below

2022-12-15 03:44 UTC, PHAng-DART commented on shlomobot_pytest/assertions.py
> +# THIS FILE CAN BE DELETED ALREADY AS ALL THE FUNCTIONS HAVE BEEN MOVED TO COMMON TESTS
Done

2022-12-15 03:44 UTC, PHAng-DART commented on shlomobot_pytest/pretest.py
> +@pytest.mark.skip("Not Required")
Done

2022-12-15 03:44 UTC, PHAng-DART commented on shlomobot_pytest/pretest.py
> +    file_function_map,
Done

2022-12-15 07:05 UTC, maxandron requested changes
Well done! This is exactly what I had in mind.
Fix the two small comments I left and run "black" on the files for formatting

2022-12-15 07:05 UTC, maxandron commented on shlomobot_pytest/pretest.py
> +    FILE_FUNCTION_MAP: dict[str, list[str]]=dict(),
Use lowercase variable names as parameters

Same goes for the `MODULE_SCOPE` above

2022-12-15 07:05 UTC, maxandron commented on shlomobot_pytest/assertions.py
> +# THIS FILE CAN BE DELETED ALREADY AS ALL THE FUNCTIONS HAVE BEEN MOVED TO COMMON TESTS
Done, but you forgot to commit?

2022-12-15 07:13 UTC, PHAng-DART commented on shlomobot_pytest/assertions.py
> +# THIS FILE CAN BE DELETED ALREADY AS ALL THE FUNCTIONS HAVE BEEN MOVED TO COMMON TESTS
Oh right

2022-12-15 07:15 UTC, PHAng-DART commented on shlomobot_pytest/pretest.py
> +    FILE_FUNCTION_MAP: dict[str, list[str]]=dict(),
Done

2022-12-15 07:36 UTC, merged