added test to look for loops
DARTSG/shlomobot_pytest pull request #9
Opened 2022-11-15 01:23 UTC by ronpeer

2022-11-16 06:06 UTC, KeshetS requested changes

2022-11-16 06:06 UTC, KeshetS commented on shlomobot_pytest/common_tests.py
> +def contains_loops(file_list: list[str], function_name_list: list[str]) -> bool:
Better to split it into two functions. One that will check for for loops, and one for while loop.
In addition, the function currently returns True even when there are no loops in the code at all.

2022-11-16 06:47 UTC, maxandron commented on shlomobot_pytest/common_tests.py
> +def contains_loops(file_list: list[str], function_name_list: list[str]) -> bool:
Also consider what happens if any of the functions in the function_names is not contained in any module

2022-11-23 08:32 UTC, KeshetS requested changes

2022-11-23 08:32 UTC, KeshetS commented on shlomobot_pytest/common_tests.py
> +GLOBAL_DECLERATION_REGEX = re.compile(r"\n\s*global\s+[^\W]+(?:\s*,\s*[^\W]+\s*)*\n")
The regex doesn't work.

2022-11-25 03:45 UTC, kjdart commented on shlomobot_pytest/common_tests.py
> +GLOBAL_DECLERATION_REGEX = re.compile(r"\n\s*global\s+[^\W]+(?:\s*,\s*[^\W]+\s*)*\n")
Fixed in latest commit

2022-11-25 05:53 UTC, KeshetS requested changes

2022-11-25 05:53 UTC, KeshetS commented on shlomobot_pytest/common_tests.py
> +        if instruction.opname != "CALL_FUNCTION":
Instead of using != and continue, why not use == and put the rest of the relevant code lines here?

2022-11-25 06:01 UTC, KeshetS approved these changes

2022-11-25 06:09 UTC, KeshetS approved these changes

2022-11-25 06:44 UTC, kjdart commented on shlomobot_pytest/common_tests.py
> +        if instruction.opname != "CALL_FUNCTION":
Changed in latest commit

2022-11-25 07:02 UTC, KeshetS approved these changes

2022-11-25 07:05 UTC, KeshetS approved these changes

2022-11-25 07:43 UTC, merged